// Release signing for Google Play (upload key), kept outside the repo.
//
// android/ is generated by `expo prebuild`, so this plugin re-applies the signing config on
// every prebuild (also with --clean). The values come from Gradle properties, normally
// ~/.gradle/gradle.properties on the build machine:
//
//   MIROBE_UPLOAD_STORE_FILE=/Users/eren/.personal-dev/android/mirobe-upload.jks
//   MIROBE_UPLOAD_KEY_ALIAS=mirobe-upload
//   MIROBE_UPLOAD_STORE_PASSWORD=…
//   MIROBE_UPLOAD_KEY_PASSWORD=…
//
// Without them a release build falls back to the debug key (fine for a local test APK, and Play
// rejects such an upload), and Gradle prints a warning.
const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = '// @mirobe/release-signing';

const SIGNING_CONFIG = `
        ${MARKER}
        release {
            if (project.hasProperty('MIROBE_UPLOAD_STORE_FILE')) {
                storeFile file(project.property('MIROBE_UPLOAD_STORE_FILE'))
                storePassword project.property('MIROBE_UPLOAD_STORE_PASSWORD')
                keyAlias project.property('MIROBE_UPLOAD_KEY_ALIAS')
                keyPassword project.property('MIROBE_UPLOAD_KEY_PASSWORD')
            }
        }`;

const RELEASE_SIGNING = `signingConfig project.hasProperty('MIROBE_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug
            if (!project.hasProperty('MIROBE_UPLOAD_STORE_FILE')) {
                logger.warn('Mirobe: MIROBE_UPLOAD_* Gradle properties are missing, release is signed with the DEBUG key (not uploadable to Play).')
            }`;

function applySigning(gradle) {
  if (gradle.includes(MARKER)) return gradle;

  // 1. A `release` entry after the generated `debug` one in signingConfigs.
  const debugSigning = /(signingConfigs\s*\{\s*debug\s*\{[^}]*\})/;
  if (!debugSigning.test(gradle)) throw new Error('withReleaseSigning: signingConfigs { debug { … } } not found in app/build.gradle');
  gradle = gradle.replace(debugSigning, `$1${SIGNING_CONFIG}`);

  // 2. buildTypes.release uses it instead of the debug key.
  const releaseBuildType = /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/;
  if (!releaseBuildType.test(gradle)) throw new Error('withReleaseSigning: buildTypes { release { signingConfig … } } not found in app/build.gradle');
  return gradle.replace(releaseBuildType, `$1${RELEASE_SIGNING}`);
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (mod) => {
    if (mod.modResults.language !== 'groovy') throw new Error('withReleaseSigning: only a Groovy app/build.gradle is supported');
    mod.modResults.contents = applySigning(mod.modResults.contents);
    return mod;
  });
};

module.exports.applySigning = applySigning;
